### PR TITLE
Recipe App

### PR DESCRIPTION
**Pull request by karam084**
### Project requirements

-  You should follow the layout of the wireframes provided. You should personalize the rest of the design including colors, typographies, spacings, etc.
- Login page and registration page:
   - Should be built with Devise.
- Food list:
   - Should display a list of food added by the logged-in user as in the wireframe (for teams with only 2 people    display also quantity of a given food).
   - Should lead to a form that allows users to add new food.
- Recipes list:
  - Should display a list of recipes created by the logged-in user as in the wireframe.
  - Should lead to recipe details.
  - If the user is the owner of the recipe, should allow the user to delete it. 
- Public recipe list:
  - Should display a list of all public recipes ordered by newest as in the wireframe.
  - Should lead to recipe details.
- Recipe details:
  - If the recipe is public or the user is the owner of the recipe, should display the recipe details as in the wireframe.
  - If the user is the owner of the recipe, should lead to the form that allows the user to add new food.

- General shopping list view:
  - Should show the list of food that is missing for all recipes of the logged-in user (compare the list of food for all recipes with the general food list of that user).
  - Should count the total food items and total price of the missing food.

### CODE REVIEW

**Review by danielufeli — CHANGES_REQUESTED** [review]
Hi @karam084 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have the new Read me template, kindly use the new readme template [here](https://github.com/microverseinc/readme-template)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by Lucas-Masaba — CHANGES_REQUESTED** [review]
Hello @karam084  👋 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️ 

- [ ] The previous code reviewer did not mention it but when I look at your commits, I see you are the only contributor. If you are working alone on a project because your partner is not available, you are required to add a screenshot from student success approving that you were allowed to work alone on a project.

### [OPTIONAL]
- I see you have a `dev` branch and `update` branch. It is kind of confusing because, in GitFlow, the development branch is usually named `dev` branch. If you can, please confirm that the `update` branch is your development branch 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by fobadara — COMMENTED** [review]
Hi @karam084, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have commits from your partner. Kindly fix this as suggested by previous reviewers.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Lucas-Masaba** [comment]
@fobadara ,@karam084 added the screenshot to prove that student success allowed him to work solo on his README

**Comment by karam084** [comment]
Hi @fobadara ,
Kindly be informed that I added approval from Microvers to work solo this week because I didn't have any partners to work with them.
Thank you

**Review by Lucas-Masaba — APPROVED** [review]
# Hello @karam084 👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

almost-there

## Highlights 🍾 
- Linter checks passing 🏄 
- The UI looks clean 🧹 
- The application is working like it is supposed to 👍 

## Optional suggestions 💭 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by karam084** [comment]
Thank you

**Pull request merged**
